blank_issues_enabled: false

contact_links:
  - name: Ask an question / advise on using proxify
    url: https://github.com/projectdiscovery/proxify/discussions/categories/q-a
    about: Ask a question or request support for using proxify

  - name: Share idea / feature to discuss for proxify
    url: https://github.com/projectdiscovery/proxify/discussions/categories/ideas
    about: Share idea / feature to discuss for proxify

  - name: Connect with PD Team (Discord)
    url: https://discord.gg/projectdiscovery
    about: Connect with PD Team for direct communication